### ISSUE TITLE
2.13 V2 Overwrite issue

### ISSUE THREAD

**Issue by iven86** [rkruk/RaspberryPiWeatherDisplay#7]
Hi, with time update place I faced the minutes' numbers merged with previews number without removing the old one

**Comment by rkruk** [comment]
I'm aware of this problem - though I still have to look into that when I'll find some spare time. It is a problem with refresh() function in the python library. To avoid that temporarily you could use full.refresh every minute, but I wouldn't recommend that approach as it is just avoiding the main problem and the effect is a bit ugly. The 'partial refresh' python code is responsible for handling screen overwrite issue. Though as I mention I'll have yet to look into it.

**Comment by rkruk** [comment]
The issue was mentioned in #https://github.com/rkruk/RaspberryPiWeatherDisplay/issues/2#issue-626005942. This issue has to be closed as it has already been broad up by me in issue n:2.
